### ISSUE TITLE
Game Biome Crash - JustSticky

### ISSUE THREAD

**Issue by JustSticky** [ChezCoder/moose-mod-fabric#4]
**Describe the bug**
The game crashes if you have the 21w17a pre-release of the Moose Mod.

**To Reproduce**
1. Start the game with the mod.

**Expected behavior**
I expected the game to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/82414099/116750844-1590c400-a9d1-11eb-94b1-d44ff707bdef.png)

**Version Info (please complete the following information):**
 - OS: Windows 10
 - MC Version 1.16.5
 - Mod Version 21w17a

**Additional information**
Ok

**Comment by ChezCoder** [comment]
Resolving this issue in next commit/build
